services:
    web:
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html
        networks:
            - webnet
        depends_on:
            - db

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: epignosis-test
        volumes:
            - db_data:/var/lib/mysql
            - ./epignosis-test.sql:/docker-entrypoint-initdb.d/epignosis-test.sql
        networks:
            - webnet

networks:
    webnet:
        driver: bridge

volumes:
    db_data:
        driver: local
